// int age = 20;
// double gpa = 4.5;
// bool isStudent = true;
// string name = "Иван";

// Console.WriteLine(name);
// Console.WriteLine(age);
// Console.WriteLine(gpa);
// Console.WriteLine(isStudent);
// string firstName = "Полина";
// string lastName = "Домрачева";
// string group = "Исп-241";
// int birthdayYear = 2008;
// double gpa = 4;
// bool hasScholarship = true;
// int currentYear = 2026;
// int age = currentYear - birthdayYear;
// Console.WriteLine("Студенческое удостоверение");
// Console.WriteLine($"Имя:{firstName} {lastName}");
// Console.WriteLine($"группа:{group}");
// Console.WriteLine($"возраст:{age} лет");
// Console.WriteLine($"средний балл:{gpa} ");
// Console.WriteLine($"стипендия:{hasScholarship}");
// Console.Write("\nВведите ваш любимый предмет: ");
// string subject = Console.ReadLine();
// Console.WriteLine($"Отлично! {firstName} любит {subject}. ");
int a = 15;
int b = 4;
Console.WriteLine($"Сумма: {a + b}");
Console.WriteLine($"Разность: {a - b}");
Console.WriteLine($"Произведение: {a * b}");
Console.WriteLine($"Частное(int): {a / b}");
Console.WriteLine($"Остаток: {a % b}");
double result = (double)a / b;
Console.WriteLine($"Частное (double): {result}");
Console.WriteLine("Калькулятор");
Console.WriteLine("Введите первое число: ");
double num1 = double.Parse(Console.ReadLine());
Console.WriteLine("Введите второе число: ");
double num2 = double.Parse(Console.ReadLine());
Console.WriteLine($"Сумма: {num1 + num2}");
Console.WriteLine($"Разность: {num1 - num2}");
Console.WriteLine($"Произведение: {num1 * num2}");
if (num2 != 0)
    Console.WriteLine($"Частное: {num1 / num2}");
else
    Console.WriteLine("Деление на ноль невозможно!");