// int age = 20;
// double gpa = 4.5;
// bool isStudent = true;
// string name = "Иван";

// Console.WriteLine(name);
// Console.WriteLine(age);
// Console.WriteLine(gpa);
// Console.WriteLine(isStudent);
// string firstName = "Полина";
// string lastName = "Домрачева";
// string group = "Исп-241";
// int birthdayYear = 2008;
// double gpa = 4;
// bool hasScholarship = true;
// int currentYear = 2026;
// int age = currentYear - birthdayYear;
// Console.WriteLine("Студенческое удостоверение");
// Console.WriteLine($"Имя:{firstName} {lastName}");
// Console.WriteLine($"группа:{group}");
// Console.WriteLine($"возраст:{age} лет");
// Console.WriteLine($"средний балл:{gpa} ");
// Console.WriteLine($"стипендия:{hasScholarship}");
// Console.Write("\nВведите ваш любимый предмет: ");
// string subject = Console.ReadLine();
// Console.WriteLine($"Отлично! {firstName} любит {subject}. ");
// int a = 15;
// int b = 4;
// Console.WriteLine($"Сумма: {a + b}");
// Console.WriteLine($"Разность: {a - b}");
// Console.WriteLine($"Произведение: {a * b}");
// Console.WriteLine($"Частное(int): {a / b}");
// Console.WriteLine($"Остаток: {a % b}");
// double result = (double)a / b;
// Console.WriteLine($"Частное (double): {result}");
// Console.WriteLine("Калькулятор");
// Console.WriteLine("Введите первое число: ");
// double num1 = double.Parse(Console.ReadLine());
// Console.WriteLine("Введите второе число: ");
// double num2 = double.Parse(Console.ReadLine());
// Console.WriteLine($"Сумма: {num1 + num2}");
// Console.WriteLine($"Разность: {num1 - num2}");
// Console.WriteLine($"Произведение: {num1 * num2}");
// if (num2 != 0)
//     Console.WriteLine($"Частное: {num1 / num2}");
// else
//     Console.WriteLine("Деление на ноль невозможно!");
// Console.WriteLine(int.MaxValue);
// Console.WriteLine(int.MinValue);
// Console.WriteLine(double.MaxValue);
// Console.WriteLine(double.MinValue);
Console.WriteLine("Добро пожаловать в анкету!");
Console.Write("Введите ваше имя: ");
string name = Console.ReadLine();
Console.Write("Введите вашу фамилию: ");
string surname = Console.ReadLine();
Console.Write("Введите вашу группу: ");
string group = Console.ReadLine();
Console.Write("Введите ваш год рождения: ");
int birthdayYear = int.Parse(Console.ReadLine());
Console.Write("Введите ваш средний балл(например, 4.5): ");
double gpa = double.Parse(Console.ReadLine());
int currentYear = 2026;
int age = currentYear - birthdayYear;
bool isExcellent = gpa >= 4.5;
string status = isExcellent ? "Отличник" : "Хорошист";
Console.WriteLine("Ваша анкета");
Console.WriteLine($"Имя:     {name} {surname}");
Console.WriteLine($"Группа:     {group}");
Console.WriteLine($"Возраст:     {age} лет");
Console.WriteLine($"Средний балл:     {gpa}");
Console.WriteLine($"Статус:     {status} ");
Console.WriteLine($"Лет до 30:     {30 - age} ");
Console.WriteLine("Нажмите Enter для выхода ...");
Console.ReadLine();